<style>
    .n1ed-button.n1ed-button--primary {
        background-color: #007FFF;
        border-color: #007FFF;
        color: white;
    }
</style>
<div id="cms-conf-placeholder"></div>
<div style="display: flex; justify-content: right;">
    <button id='n1edSave' type="button" class="n1ed-button n1ed-button--primary"><span>Save</span></button>
</div>

<script src='https://n1ed.com/js/n1ed-cms-conf-3.js'></script>
<script>
  function findAdminURL() {
    let regexp = new RegExp('admin*');
    let path = window.location.pathname.split("/");
    return path.find(p => regexp.test(p));
  }

  function URLPrecedingsDetect() {
    let regexp = new RegExp("index*");
    let path = window.location.pathname.split("/");
    return path.find((p) => regexp.test(p));
  }

  let adminURL;

  if (URLPrecedingsDetect())
    adminURL = `${URLPrecedingsDetect()}/${findAdminURL()}`;
  else
    adminURL = `${findAdminURL()}`;

  var authUrl = `/${adminURL}/edsdk/auth/save`;
  var funcSave = window.attachN1EDCmsConf({
    el: document.getElementById("cms-conf-placeholder"),
    urlSetApiKeyAndToken: authUrl,
    apiKey: '<?php echo $this->getApi(); ?>',
    token: '<?php echo $this->getToken(); ?>',
    editorName: 'tinymce',
    integration: 'magento',
    isCheckBoxN1EDEcoEnabledVisible: false,
    checkBoxN1EDEcoEnabledTitle: null,
    checkBoxN1EDEcoEnabledValue: null,
    onN1EDEcoEnabledChange: function (value, onFinished) {},
    onApiKeyChange: function (apiKey, token) {}
  });


  document.getElementById('n1edSave').addEventListener('click', () => {
    funcSave((e) => {
      if (e)
        alert('Configuration saved');
      else
        alert('Error: configuration was not save');
    });
  });
</script>