<div id="cms-conf-placeholder"></div>


<script src='https://n1ed.com/js/n1ed-cms-conf-3.js'></script>
<script>
function findAdminURL(){
  let regexp = new RegExp('admin*');
  let path = window.location.pathname.split("/");
  return path.find(p => regexp.test(p));
}

function URLPrecedingsDetect() {
        let regexp = new RegExp("index*");
        let path = window.location.pathname.split("/");
        return path.find((p) => regexp.test(p));
      }

      let adminURL;

      if (URLPrecedingsDetect()) {
        adminURL = `${URLPrecedingsDetect()}/${findAdminURL()}`;
      } else {
        adminURL = `${findAdminURL()}`;
      }

var authUrl = `/${adminURL}/edsdk/auth/save`;
window.attachN1EDCmsConf({
        el: document.getElementById("cms-conf-placeholder"),
        urlSetApiKeyAndToken:  authUrl,
        apiKey: '<?php echo $this->getApi(); ?>',
        token: '<?php echo $this->getToken(); ?>',
        editorName: 'tinymce', // or 'ckeditor' if you use it as base editor
        integration: 'magento', // your CMS name in lowercase, type once and do not change in future please
        isCheckBoxN1EDEcoEnabledVisible: false,
        checkBoxN1EDEcoEnabledTitle: null,
        checkBoxN1EDEcoEnabledValue: null,
        onN1EDEcoEnabledChange: function (value, onFinished) {},
        onApiKeyChange: function (apiKey, token) {}
      });
</script>